#define SCR_WIDTH_DEFAULT 214
#define SCR_HEIGHT_DEFAULT 120

// PERFORMANCE OPTIONS

#define RENDER_DIST 20
#define TEXTURE_RES 16

#define WORLD_SIZE 64
#define WORLD_HEIGHT 64

#define WORLD_WRAP

#define SCR_DETAIL 2

// END OF PERFORMANCE OPTIONS

#define X 0
#define Y 1
#define Z 2

#define BLOCK_AIR 0
#define BLOCK_GRASS 1
#define BLOCK_DIRT 2
#define BLOCK_STONE 3
#define BLOCK_BRICKS 4
#define BLOCK_WOOD 5
#define BLOCK_LEAVES 6

#define PLAYER_REACH 5.0f
#define FOV 90.0f

#define SHADER_UNIFORM_c 0
#define SHADER_UNIFORM_d 1
#define SHADER_UNIFORM_e 2
#define SHADER_UNIFORM_g 3
#define SHADER_UNIFORM_r 4
#define SHADER_UNIFORM_P 5
#define SHADER_UNIFORM_W 6
#define SHADER_UNIFORM_T 7
#define SHADER_UNIFORM_b 8
